Add user-based auth flag to contributor docs
memphisdev/memphis pull request #1191
Opened 2023-08-01 03:54 UTC by rnowling-memphis

2023-08-01 04:53 UTC, idanasulinmemphis requested changes

2023-08-01 04:53 UTC, idanasulinmemphis commented on CONTRIBUTING.md
> +USER_PASS_BASED_AUTH="true" DEV_ENV="true" DOCKER_ENV="true" ANALYTICS="false" go run main.go
We can omit the ANALYTICS as well

2023-08-01 20:20 UTC, rnowling-memphis commented on CONTRIBUTING.md
> +USER_PASS_BASED_AUTH="true" DEV_ENV="true" DOCKER_ENV="true" ANALYTICS="false" go run main.go
Done!

2023-08-02 03:21 UTC, idanasulinmemphis approved these changes

2023-08-02 03:21 UTC, merged