remove all unnecessary logic of github & function in oss
memphisdev/memphis pull request #1323
Opened 2023-09-19 19:40 UTC by shohamroditimemphis

2023-09-27 11:32 UTC, shay23b requested changes

2023-09-27 11:32 UTC, shay23b commented on server/source_code_management_cloud.go
> +		"repo_name":  "memphis-dev-functions",
use consts

2023-09-28 08:54 UTC, shay23b approved these changes
backend approved

2023-10-01 08:00 UTC, avrhamNeeman approved these changes

2023-10-01 08:03 UTC, idanasulinmemphis approved these changes

2023-10-01 08:08 UTC, merged