add integrations audit logs
memphisdev/memphis pull request #1345
Opened 2023-09-27 07:40 UTC by shay23b

2023-09-27 10:05 UTC, daniel-davidd requested changes

2023-09-27 10:05 UTC, daniel-davidd commented on server/jetstream.go
> +		// case integrationsAuditLogsStream:
Should it be on comment?

2023-09-27 10:05 UTC, daniel-davidd commented on server/memphis_handlers_integrations.go
> +	durableName := "$memphis_integrations_audit_logs_consumer_" + uid
use the INTEGRATIONS_AUDIT_LOGS_CONSUMER const

2023-09-27 11:52 UTC, daniel-davidd approved these changes

2023-09-27 11:58 UTC, daniel-davidd approved these changes

2023-10-01 11:09 UTC, idanasulinmemphis approved these changes

2023-10-01 11:15 UTC, merged